# Generated by Django 4.1.6 on 2023-11-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alumno_delete_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor')], default='alumno', max_length=10, verbose_name='Rol'),
        ),
    ]
