# Generated by Django 4.0.1 on 2023-11-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_curso_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(related_name='cursos', to='core.Alumno'),
        ),
    ]
